# yaml-language-server: $schema=https://raw.githubusercontent.com/buildwithgrove/path/refs/heads/main/config/config.schema.yaml

shannon_config:
  full_node_config:
    # Connect to local Shannon testnet node
    rpc_url: "http://shannon-testnet-node:26657"
    grpc_config:
      host_port: "shannon-testnet-node:9090"
      insecure: true  # Local connection, no TLS needed
      backoff_base_delay: "1s"
      backoff_max_delay: "120s"
      min_connect_timeout: "20s"
      keep_alive_time: "20s"
      keep_alive_timeout: "20s"
    lazy_mode: false

  gateway_config:
    # Centralized mode for testing - gateway signs and uses apps you control
    gateway_mode: "centralized"
    gateway_address: "pokt1gzpeptmukzxk3ma44q300q9fa5nzjy80wgglxc"
    gateway_private_key_hex: "203d1163d27f239d081dfc71b113b91cd7ed57358c32791bdd7777d05638a9ed"
    owned_apps_private_keys_hex:
      - "0000000000000000000000000000000000000000000000000000000000000001"
      # Add more app keys if you have multiple apps

  # Optional fallback for services (if protocol runs out of valid endpoints)
  # service_fallback:
  #   - service_id: eth
  #     send_all_traffic: false
  #     fallback_urls:
  #       - "https://eth.rpc.grove.city/v1/your-token"
  #       - "https://other.endpoint/..."
  
router_config:
  # HTTP port where PATH listens
  port: 3069
  # Enable CORS for web applications
  cors:
    allowed_origins: ["*"]
    allowed_methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
    allowed_headers: ["*"]

logger_config:
  level: "info"
  format: "json"
