# yaml-language-server: $schema=https://raw.githubusercontent.com/buildwithgrove/path/refs/heads/main/config/config.schema.yaml

shannon_config:
  full_node_config:
    # Use local node instead of external Grove endpoints
    rpc_url: "http://shannon-testnet-node:26657"
    grpc_config:
      host_port: "shannon-testnet-node:9090"
      insecure: true  # Local connection, no TLS required
      backoff_base_delay: "5s"
      backoff_max_delay: "120s"
      min_connect_timeout: "20s"
      keep_alive_time: "20s"
      keep_alive_timeout: "20s"
    lazy_mode: false

  gateway_config:
    # Use centralized mode with test keys
    gateway_mode: "centralized"
    gateway_address: "pokt1czzkp4at00ep6ygk49f97w2znhjgq8l3vp7tn8"
    gateway_private_key_hex: "0x0000000000000000000000000000000000000000000000000000000000000001"
    owned_apps_private_keys_hex:
      - "0x0000000000000000000000000000000000000000000000000000000000000001"

router_config:
  # HTTP port where PATH listens
  port: 3069
  # Enable CORS for web applications
  cors:
    allowed_origins: ["*"]
    allowed_methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
    allowed_headers: ["*"]

logger_config:
  level: "debug"
  format: "json"